# Generated by Django 4.0.5 on 2022-06-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=0, max_length=100)),
                ('user_name', models.CharField(default=0, max_length=100)),
                ('email', models.CharField(default=0, max_length=100)),
                ('dob', models.CharField(default=0, max_length=100)),
                ('password', models.CharField(default=0, max_length=100)),
                ('confirm_password', models.CharField(default=0, max_length=100)),
                ('clock_in', models.CharField(default=0, max_length=100)),
                ('clock_out', models.TimeField(auto_now=True)),
            ],
        ),
    ]
